apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: 865893227318.dkr.ecr.us-east-1.amazonaws.com/flask_argocd:3
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: dockersecret  

---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service
  namespace: argocd
spec:
  type: LoadBalancer
  selector:
    app: my-flask-app
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080

